pool:
  name: Azure Pipelines
  
trigger:
 - ''

stages:
- stage: CreateCloudformation
  displayName: Build and Create Cloudformation
  jobs:
  - job: FailoverRDSDatabase
    variables:
    - group: guacamole-dev
    pool:
      name: Azure Pipelines
      vmImage: 'ubuntu-latest'
    steps:
      - task: AWSCLI@1
        displayName: Failover the RDS Database
        condition:  eq(variables['DR_TEST'], 'Yes') 
        inputs:
          awsCredentials: 'Azure-LinxAcc'
          regionName: $(REGION)
          awsCommand: 'rds'
          awsSubCommand: 'reboot-db-instance'
          awsArguments: '--db-instance-identifier $(DBNAME) --force-failover'
      - task: AWSCLI@1
        displayName: Wait for RDS Database Available
        condition:  eq(variables['DR_TEST'], 'Yes') 
        inputs:
          awsCredentials: 'Azure-LinxAcc'
          regionName: $(REGION)
          awsCommand: 'rds'
          awsSubCommand: 'wait' 
          awsArguments: 'db-instance-available --db-instance-identifier $(DBNAME)'
  - job: BuildStack
    variables:
    - group: guacamole-dev
    pool:
      name: Azure Pipelines
      vmImage: 'ubuntu-latest'
    steps:
      - task: AWSShellScript@1 
        displayName: Configure environment
        inputs:
          awsCredentials: 'Azure-LinxAcc'
          regionName: $(REGION)
          scriptType: 'filePath'
          filePath: 'guacamole_code/config_environment.sh'
      - task: CloudFormationCreateOrUpdateStack@1
        displayName: Create Cloudformation stack
        inputs:
          awsCredentials: 'Azure-LinxAcc'
          regionName: $(REGION)
          stackName: $(StackName)
          logRequest: true
          logResponse: true
          templateSource: 'file'
          templateFile: 'guacamole_code/guacamole_cloudformation.yml'
          templateParametersSource: 'inline'
          templateParameters: |
            - ParameterKey: DBNAME
              ParameterValue: $(DBNAME)
            - ParameterKey: DBUSER
              ParameterValue: $(DBUSER)
            - ParameterKey: DBPASSWD
              ParameterValue: $(DBPASSWD)   
            - ParameterKey: DBVERSION
              ParameterValue: $(DBVERSION)           
            - ParameterKey: MYSQLUSER
              ParameterValue: $(MYSQLUSER)
            - ParameterKey: MYSQLPASSWD
              ParameterValue: $(MYSQLPASSWD)
            - ParameterKey: AMIID
              ParameterValue: $(AMIID)
            - ParameterKey: InstanceType
              ParameterValue: $(InstanceType)
            - ParameterKey: KeyName
              ParameterValue: $(KeyName)             
            - ParameterKey: LoadBalancerCertificateArn
              ParameterValue: $(LoadBalancerCertificateArn)
            - ParameterKey: MyVPC
              ParameterValue: $(MyVPC)
            - ParameterKey: RDSInstanceType
              ParameterValue: $(RDSInstanceType)
            - ParameterKey: SubnetID1
              ParameterValue: $(SubnetID1)
            - ParameterKey: SubnetID2
              ParameterValue: $(SubnetID2) 
            - ParameterKey: JKSTOREPASSWD
              ParameterValue: $(JKSTOREPASSWD) 
            - ParameterKey: DBSnapshotIdentifier
              ParameterValue: $(DBSnapshotIdentifier)  
            - ParameterKey: Application
              ParameterValue: $(Application)   
            - ParameterKey: EC2DOMAIN
              ParameterValue: $(EC2DOMAIN)  
            - ParameterKey: HOSTNAME1
              ParameterValue: $(HOSTNAME1) 
            - ParameterKey: HOSTNAME2
              ParameterValue: $(HOSTNAME2)       
      - task: AWSShellScript@1
        displayName: Tag root volumes
        inputs:
          awsCredentials: 'Azure-LinxAcc'
          regionName: $(REGION)
          scriptType: 'inline'
          inlineScript: |
            set -x
            EC2_VOLUMES=$(aws ec2 describe-instances --region "$(REGION)" --filter "Name=tag:Application,Values=$(Application)" --query "Reservations[*].Instances[*].BlockDeviceMappings[*].Ebs.[VolumeId]" --output text)
            
            while read -r RESOURCE; do
            	aws ec2 create-tags --resources "$RESOURCE" --region "$(REGION)" --tags "Key=Name,Value=${STACKNAME}-rootvolume"
                aws ec2 create-tags --resources "$RESOURCE" --region "$(REGION)" --tags "Key=Application,Value=${APPLICATION}"
            done <<< "$EC2_VOLUMES"
